top_modules:
    - fastqc:
        name: 'FastQC (raw)'
        path_filters_exclude:
            - '*_trimmed_fastqc.zip'
    - 'bbtools'
    - fastqc:
        name: 'FastQC (trimmed)'
        info: 'FastQC results after adapter trimming.'
        path_filters:
            - '*_trimmed_fastqc.zip'
