module_order:
    - fastqc:
          name: 'FastQC (raw)'
          info: 'This section of the report shows FastQC results before adapter trimming.'
          path_filters_exclude:
              - '*trimmed*.zip'
    - fastqc:
          name: 'FastQC (trimmed)'
          info: 'This section of the report shows FastQC results after adapter trimming.'
          path_filters:
              - '*trimmed*.zip'